name: Simulator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  #Allows you to start workflow manually from the actions tab in the interface github.com
  workflow_dispatch:

jobs:
  #CMake builds
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: ${{ matrix.config.shell }} {0}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        config:
          - {
              name: "Ubuntu GCC",
              os: ubuntu-latest,
              shell: "bash",
              generator: "Unix Makefiles",
              cc: "gcc",
              cxx: "g++",
              cxx_flags: "",
              cxx_standard: 17,
              build_type: Release,
            }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: >
          cmake -B build-simulator
          -G "${{ matrix.config.generator }}"
          -A "${{ matrix.config.arch }}"
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
          -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
          -S ./simulator

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build build-simulator --config ${{ matrix.config.build_type }} --parallel

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: gw_simulator_${{ matrix.config.name }}
          path: "build-simulator/*"
          include-hidden-files: true
          overwrite: true

      - name: Test
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest --test-dir build-simulator --build-config ${{ matrix.config.build_type }} --output-on-failure
